### ISSUE TITLE
Cross page boundary?

### ISSUE THREAD

**Issue by ilg-ul** [keith-packard/riscv-semihosting-spec#1]
> On systems with paging support, this sequence must not cross a page boundary as the semihosting system must be able to check for the semihosting sequence without needing data from potentially missing pages.

This is another complication caused by the lack of multiple EBREAK instructions.

I think that simply mentioning this restriction is not enough, it must be accompanied by a code snippet showing how to implement it.

Do you know of any assembler directives that can be used to ask the linker to guarantee that the 3 instructions are placed in a single page? I'm thinking of something like enforcing a 16-byte alignement by eventually inserting 1-2 nops in front of it?

Since the alternative is to use a separate memory section, manually placed in the linker script at an address that is known to be in a single page, a major complication I would say.

**Comment by keith-packard** [comment]
Good question. Jim Wilson suggested the solution to this problem -- place the semihosting sequence in a function and align that to ensure that the semihosting sequence doesn't cross a page boundary. I've inserted an example of how that can be done into the proposed spec.
